<div class="brand-slider">
    <?php if (!empty($brands = $block->getBrandCollection()) && count($brands)): ?>
        <div class="brand-slider-container">
            <?php foreach ($brands as $brand): ?>
                <?php if ($brand->getStatus() == 1): ?>
                <div class="brand-item" data-brand-id="<?= $escaper->escapeHtml($brand->getId()) ?>">
                    <div class="brand-logo">
                        <img src="<?= $escaper->escapeUrl($brand->getImage()) ?>"
                             alt="<?= $escaper->escapeHtml($brand->getBrandName()) ?>">
                    </div>
                    <div class="brand-name">
                        <?= $escaper->escapeHtml($brand->getBrandName()) ?>
                    </div>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p><?= $escaper->escapeHtml(__('No brands available.')); ?></p>
    <?php endif; ?>
</div>



<script>
    require([
        'jquery',
        'slick'
    ], function($) {
        $(document).ready(function() {
            $('.brand-slider-container').slick({
                slidesToShow: 4,  // Adjust based on how many images you want visible
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 1500,
                arrows: false,
                dots: true,
                infinite: true,
                pauseOnFocus: true,
                pauseOnHover: true,
                speed: 300,
                centerMode: true,  // Enable centering of the slides
                centerPadding: '40px',
            });

            $('.brand-item').on('click', function(event) {
                event.preventDefault();
                var brandId = $(this).data('brand-id');

                $.ajax({
                    url: '<?= $escaper->escapeUrl($block->getUrl('brand/index/productList')); ?>',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        brandId: brandId
                    },
                    success: function (response) {
                        if (response.success) {
                        window.location.href = '<?= $escaper->escapeUrl($block->getUrl('brand/index/products'));
                        ?>?brandId=' + encodeURIComponent(brandId);
                         }
                     },
                        error: function (xhr, status, error) {
                            console.error('AJAX error: ' + error);
                    }
                });
            });
        });
    });
</script>

<style>
.brand-item img {
    display: block; 
    max-width: 100%; 
    height: auto; 
}

.brand-item {
    width: 100%; 
    max-width: 100%; 
}

.brand-name {
    text-align: center;
    padding: 15px 0;
}

</style>
