<?php
/** @var \Magento\Catalog\Block\Product\ListProduct $block */
/** @var \Riverstone\ShopbyBrand\ViewModel\Category $viewModel */
$viewModel = $block->getViewModel();
$moduleStatus = $viewModel->getModuleEnable();

$showName = $viewModel->getBrandName();
$showLogo = $viewModel->getBrandLogo();
$showDescription = $viewModel->getBrandDescription();
?>

<?php if (!$block->getLoadedProductCollection()->count()): ?>
    <div class="message info empty">
        <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($block->getLoadedProductCollection() as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info"
                         id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                         data-container="product-<?= /* @noEscape */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= $block->escapeHtml($_product->getName()) ?>
                                </a>
                            </strong>
                            <?php
                            if ($moduleStatus) {
                            $brandDetails = $viewModel->getBrandDetails($_product);
                            if (!empty($brandDetails)): ?>
                                <div class="product-brand">
                                    <?php if ($showName && !empty($brandDetails['name'])): ?>
                                        <h2 class="brand-name">
                                            <?= $block->escapeHtmlAttr($brandDetails['name']); ?>
                                        </h2>
                                    <?php endif; ?>
                                    <?php if ($showLogo && !empty($brandDetails['image'])): ?>
                                        <div class="brand-image">
                                            <img src="<?= $block->escapeUrl($brandDetails['image']); ?>"
                                                    alt="<?= $block->escapeHtml($brandDetails['name']); ?>">
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($showDescription && !empty($brandDetails['description'])): ?>
                                        <div class="brand-description">
                                            <?= $block->escapeHtml($brandDetails['description']); ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        <?php } ?>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= $block->getProductPrice($_product) ?>

                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                  method="post">
                                                <input type="hidden" name="product"
                                                       value="<?= $block->escapeHtml($postParams['data']['product']) ?>">
                                                <input type="hidden" name="<?= \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?= $block->escapeHtml($postParams['data'][\Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED]) ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="actions-secondary">
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Design": {}
        }
    }
</script>

<style>
h2.brand-name {
    font-size: 15px;
}
.brand-image {
    width: 50px;
}
h2 {
    font-weight: 300;
    line-height: 0.1;
    margin-bottom: 1rem;
}

</style>
