<?php
/** @var \Riverstone\ShopbyBrand\Block\Brand\BrandList $block */
$brandCollection = $block->getBrandCollection();
$customerGroupId = $block->getCustomerGroupId();
$storeId = $block->getStoreId();
?>

<?php if ($brandCollection->getSize()): ?>
    <div class="brand-list">
        <?php foreach ($brandCollection as $brand): ?>
            <?php
                $brandCustomerGroups = json_decode($brand->getCustomerGroup(), true);
                $brandStores = json_decode($brand->getStore(), true);
            ?>
            <?php if ($brand->getStatus() == 1): ?>
                <div class="brand-item" data-brand-id="<?= $escaper->escapeHtml($brand->getId()) ?>">
                    <div class="brand-logo">
                        <img src="<?= $escaper->escapeUrl($brand->getImage()) ?>" 
                        alt="<?= $escaper->escapeHtml($brand->getBrandName()) ?>">
                    </div>
                    <div class="brand-name">
                        <?= $escaper->escapeHtml($brand->getBrandName()) ?>
                    </div>
                    <div class="brand-name">
                        <?= $escaper->escapeHtml($brand->getDescription()) ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <div class="message info">
        <div><?= $escaper->escapeHtml(__('No brands available at the moment.')) ?></div>
    </div>
<?php endif; ?>

<script>
    require(['jquery'], function($) {
        $(document).ready(function () {
            $('.brand-item').on('click', function (e) {
                e.preventDefault(); // Prevent the default action of the event
                var brandId = $(this).data('brand-id');
                console.log(brandId);
                console.log('test');
                $.ajax({
                    url: '<?= $escaper->escapeUrl($block->getUrl('brand/index/productList')); ?>',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        brandId: brandId
                    },
                    success: function (response) {
                        if (response.success) {
                            // Redirect to product list page with brand ID as query parameter
                            window.location.href = 
                                '<?= $escaper->escapeUrl($block->getUrl('brand/index/products')); ?>' + 
                                '?brandId=' + encodeURIComponent(brandId);
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error('AJAX error: ' + error);
                    }
                });
            });
        });
    });
</script>

<style>
.brand-list {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 20px;
}

.brand-logo img {
    width: 100%; /* Set a fixed width */
    height: auto; /* Set a fixed height */
}

.brand-name {
  padding: 10px 0;
}

.brand-item {
    text-align: center;
}
</style>
